# Generated by Django 3.0 on 2019-12-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='profile-pics'),
        ),
    ]
