# Generated by Django 3.0 on 2019-12-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_updoots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updoots',
            field=models.FloatField(default=0),
        ),
    ]
