# Generated by Django 3.0 on 2019-12-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191231_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updoots',
            field=models.SmallIntegerField(default=0),
        ),
    ]
